
package br.com.m3Tech.solucoesFromtis.certificadora.webservices.retorno;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RetornoCertificacaoDigital", targetNamespace = "http://webservices.portal.fidc.fromtis.com.br/", wsdlLocation = "http://172.16.5.171/portal/retornoCertificacaoDigital?wsdl")
public class RetornoCertificacaoDigital_Service
    extends Service
{

    private final static URL RETORNOCERTIFICACAODIGITAL_WSDL_LOCATION;
    private final static WebServiceException RETORNOCERTIFICACAODIGITAL_EXCEPTION;
    private final static QName RETORNOCERTIFICACAODIGITAL_QNAME = new QName("http://webservices.portal.fidc.fromtis.com.br/", "RetornoCertificacaoDigital");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.5.171/portal/retornoCertificacaoDigital?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RETORNOCERTIFICACAODIGITAL_WSDL_LOCATION = url;
        RETORNOCERTIFICACAODIGITAL_EXCEPTION = e;
    }

    public RetornoCertificacaoDigital_Service() {
        super(__getWsdlLocation(), RETORNOCERTIFICACAODIGITAL_QNAME);
    }

    public RetornoCertificacaoDigital_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RETORNOCERTIFICACAODIGITAL_QNAME, features);
    }

    public RetornoCertificacaoDigital_Service(URL wsdlLocation) {
        super(wsdlLocation, RETORNOCERTIFICACAODIGITAL_QNAME);
    }

    public RetornoCertificacaoDigital_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RETORNOCERTIFICACAODIGITAL_QNAME, features);
    }

    public RetornoCertificacaoDigital_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RetornoCertificacaoDigital_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RetornoCertificacaoDigital
     */
    @WebEndpoint(name = "RetornoCertificacaoDigitalPort")
    public RetornoCertificacaoDigital getRetornoCertificacaoDigitalPort() {
        return super.getPort(new QName("http://webservices.portal.fidc.fromtis.com.br/", "RetornoCertificacaoDigitalPort"), RetornoCertificacaoDigital.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RetornoCertificacaoDigital
     */
    @WebEndpoint(name = "RetornoCertificacaoDigitalPort")
    public RetornoCertificacaoDigital getRetornoCertificacaoDigitalPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.portal.fidc.fromtis.com.br/", "RetornoCertificacaoDigitalPort"), RetornoCertificacaoDigital.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RETORNOCERTIFICACAODIGITAL_EXCEPTION!= null) {
            throw RETORNOCERTIFICACAODIGITAL_EXCEPTION;
        }
        return RETORNOCERTIFICACAODIGITAL_WSDL_LOCATION;
    }

}
