IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_CLIENTE_HAS_ENDERECO')
BEGIN
	CREATE TABLE TB_CLIENTE_HAS_ENDERECO(
		ID_CLIENTE INT ,
		ID_CLIENTE_ENDERECO INT
	)
END
GO

IF NOT EXISTS(SELECT * FROM TB_CLIENTE_HAS_ENDERECO)
BEGIN
	INSERT INTO TB_CLIENTE_HAS_ENDERECO(ID_CLIENTE, ID_CLIENTE_ENDERECO)
	SELECT ID_CLIENTE, ID_CLIENTE_ENDERECO FROM TB_CLIENTE c
	where NOT EXISTS (select * from TB_CLIENTE_HAS_ENDERECO CE 
					  where (ce.ID_CLIENTE = c.ID_CLIENTE
					  and ce.ID_CLIENTE_ENDERECO = c.ID_CLIENTE_ENDERECO)
					  OR c.ID_CLIENTE_ENDERECO IS NULL)

END
GO