IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_PRODUTO')
BEGIN
	CREATE TABLE TB_PRODUTO(
		ID_PRODUTO INT IDENTITY(1,1) PRIMARY KEY
	)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PRODUTO' AND COLUMN_NAME = 'NOME')
BEGIN
	ALTER TABLE TB_PRODUTO ADD NOME VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PRODUTO' AND COLUMN_NAME = 'DESCRICAO')
BEGIN
	ALTER TABLE TB_PRODUTO ADD DESCRICAO VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PRODUTO' AND COLUMN_NAME = 'VALOR')
BEGIN
	ALTER TABLE TB_PRODUTO ADD VALOR NUMERIC(17,2)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PRODUTO' AND COLUMN_NAME = 'NM_IMAGEM')
BEGIN
	ALTER TABLE TB_PRODUTO ADD NM_IMAGEM VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PRODUTO' AND COLUMN_NAME = 'IMAGEM')
BEGIN
	ALTER TABLE TB_PRODUTO ADD IMAGEM VARBINARY(MAX)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PRODUTO' AND COLUMN_NAME = 'CATEGORIA')
BEGIN
	ALTER TABLE TB_PRODUTO ADD CATEGORIA VARCHAR(255)
END
GO


IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PRODUTO' AND COLUMN_NAME = 'IC_ATIVO')
BEGIN
	ALTER TABLE TB_PRODUTO ADD IC_ATIVO BIT DEFAULT 0 NOT NULL
END
GO
