IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_CLIENTE_ENDERECO')
BEGIN
	CREATE TABLE TB_CLIENTE_ENDERECO(
		ID_CLIENTE_ENDERECO INT IDENTITY(1,1) PRIMARY KEY
	)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CLIENTE_ENDERECO' AND COLUMN_NAME = 'NUMERO')
BEGIN
	ALTER TABLE TB_CLIENTE_ENDERECO ADD NUMERO VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CLIENTE_ENDERECO' AND COLUMN_NAME = 'APELIDO')
BEGIN
	ALTER TABLE TB_CLIENTE_ENDERECO ADD APELIDO VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CLIENTE_ENDERECO' AND COLUMN_NAME = 'COMPLEMENTO')
BEGIN
	ALTER TABLE TB_CLIENTE_ENDERECO ADD COMPLEMENTO VARCHAR(255)
END
GO


IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CLIENTE_ENDERECO' AND COLUMN_NAME = 'ID_ENDERECO')
BEGIN
	ALTER TABLE TB_CLIENTE_ENDERECO ADD ID_ENDERECO INT
END
GO
