IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_FORMA_PAGAMENTO')
BEGIN
	CREATE TABLE TB_FORMA_PAGAMENTO(
		ID_FORMA_PAGAMENTO INT IDENTITY(1,1) PRIMARY KEY
	)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_FORMA_PAGAMENTO' AND COLUMN_NAME = 'NOME')
BEGIN
	ALTER TABLE TB_FORMA_PAGAMENTO ADD NOME VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_FORMA_PAGAMENTO' AND COLUMN_NAME = 'ORDENACAO')
BEGIN
	ALTER TABLE TB_FORMA_PAGAMENTO ADD ORDENACAO INT
END
GO

