IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_CONFIGURACAO_GLOBAL')
BEGIN
	CREATE TABLE TB_CONFIGURACAO_GLOBAL(
		ID_CONFIGURACAO_GLOBAL INT IDENTITY(1,1) PRIMARY KEY
	)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CONFIGURACAO_GLOBAL' AND COLUMN_NAME = 'IMPRESSORA')
BEGIN
	ALTER TABLE TB_CONFIGURACAO_GLOBAL ADD IMPRESSORA VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CONFIGURACAO_GLOBAL' AND COLUMN_NAME = 'TAXA_ENTREGA')
BEGIN
	ALTER TABLE TB_CONFIGURACAO_GLOBAL ADD TAXA_ENTREGA NUMERIC(17,2)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CONFIGURACAO_GLOBAL' AND COLUMN_NAME = 'NOME_EMPRESA')
BEGIN
	ALTER TABLE TB_CONFIGURACAO_GLOBAL ADD NOME_EMPRESA VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CONFIGURACAO_GLOBAL' AND COLUMN_NAME = 'CATEGORIA_1')
BEGIN
	ALTER TABLE TB_CONFIGURACAO_GLOBAL ADD CATEGORIA_1 VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CONFIGURACAO_GLOBAL' AND COLUMN_NAME = 'CATEGORIA_2')
BEGIN
	ALTER TABLE TB_CONFIGURACAO_GLOBAL ADD CATEGORIA_2 VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CONFIGURACAO_GLOBAL' AND COLUMN_NAME = 'CATEGORIA_3')
BEGIN
	ALTER TABLE TB_CONFIGURACAO_GLOBAL ADD CATEGORIA_3 VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CONFIGURACAO_GLOBAL' AND COLUMN_NAME = 'NU_TEL_INI')
BEGIN
	ALTER TABLE TB_CONFIGURACAO_GLOBAL ADD NU_TEL_INI INT
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CONFIGURACAO_GLOBAL' AND COLUMN_NAME = 'NU_TEL_FIM')
BEGIN
	ALTER TABLE TB_CONFIGURACAO_GLOBAL ADD NU_TEL_FIM INT
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CONFIGURACAO_GLOBAL' AND COLUMN_NAME = 'PORTA_COMM')
BEGIN
	ALTER TABLE TB_CONFIGURACAO_GLOBAL ADD PORTA_COMM VARCHAR(255)
END
GO


IF NOT EXISTS(SELECT * FROM  TB_CONFIGURACAO_GLOBAL)
BEGIN
	INSERT INTO TB_CONFIGURACAO_GLOBAL (IMPRESSORA,TAXA_ENTREGA) VALUES(null, 3.00)
END
GO

IF EXISTS(SELECT * FROM  TB_CONFIGURACAO_GLOBAL WHERE CATEGORIA_1 IS NULL )
BEGIN
	UPDATE TB_CONFIGURACAO_GLOBAL SET CATEGORIA_1 = 'CATEGORIA_1'
END
GO

IF EXISTS(SELECT * FROM  TB_CONFIGURACAO_GLOBAL WHERE CATEGORIA_2 IS NULL )
BEGIN
	UPDATE TB_CONFIGURACAO_GLOBAL SET CATEGORIA_2 = 'CATEGORIA_2'
END
GO

IF EXISTS(SELECT * FROM  TB_CONFIGURACAO_GLOBAL WHERE CATEGORIA_3 IS NULL )
BEGIN
	UPDATE TB_CONFIGURACAO_GLOBAL SET CATEGORIA_3 = 'CATEGORIA_3'
END
GO
