IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_PRODUTO_PEDIDO')
BEGIN
	CREATE TABLE TB_PRODUTO_PEDIDO(
		ID_PRODUTO_PEDIDO INT IDENTITY(1,1) PRIMARY KEY
	)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PRODUTO_PEDIDO' AND COLUMN_NAME = 'ID_PRODUTO')
BEGIN
	ALTER TABLE TB_PRODUTO_PEDIDO ADD ID_PRODUTO INT
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PRODUTO_PEDIDO' AND COLUMN_NAME = 'QUANTIDADE')
BEGIN
	ALTER TABLE TB_PRODUTO_PEDIDO ADD QUANTIDADE INT
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PRODUTO_PEDIDO' AND COLUMN_NAME = 'SUB_TOTAL')
BEGIN
	ALTER TABLE TB_PRODUTO_PEDIDO ADD SUB_TOTAL NUMERIC(19,2)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PRODUTO_PEDIDO' AND COLUMN_NAME = 'NOME')
BEGIN
	ALTER TABLE TB_PRODUTO_PEDIDO ADD NOME VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PRODUTO_PEDIDO' AND COLUMN_NAME = 'VALOR')
BEGIN
	ALTER TABLE TB_PRODUTO_PEDIDO ADD VALOR NUMERIC(19,2)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PRODUTO_PEDIDO' AND COLUMN_NAME = 'CATEGORIA')
BEGIN
	ALTER TABLE TB_PRODUTO_PEDIDO ADD CATEGORIA VARCHAR(255)
END
GO

