IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_ENTREGADOR')
BEGIN
	CREATE TABLE TB_ENTREGADOR(
		ID_ENTREGADOR INT IDENTITY(1,1) PRIMARY KEY
	)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_ENTREGADOR' AND COLUMN_NAME = 'NOME')
BEGIN
	ALTER TABLE TB_ENTREGADOR ADD NOME VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_ENTREGADOR' AND COLUMN_NAME = 'CPF_CNPJ')
BEGIN
	ALTER TABLE TB_ENTREGADOR ADD CPF_CNPJ VARCHAR(20)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_ENTREGADOR' AND COLUMN_NAME = 'NU_TELEFONE')
BEGIN
	ALTER TABLE TB_ENTREGADOR ADD NU_TELEFONE VARCHAR(20)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_ENTREGADOR' AND COLUMN_NAME = 'NU_PLACA')
BEGIN
	ALTER TABLE TB_ENTREGADOR ADD NU_PLACA VARCHAR(20)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_ENTREGADOR' AND COLUMN_NAME = 'IC_COBRAR_TAXA')
BEGIN
	ALTER TABLE TB_ENTREGADOR ADD IC_COBRAR_TAXA BIT
END
GO
