--IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_PERFIL_ACESSO')
--BEGIN
--	CREATE TABLE TB_PERFIL_ACESSO(
--		ID_PERFIL_ACESSO INT IDENTITY(1,1) PRIMARY KEY
--	)
--END
--GO
--
--IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PERFIL_ACESSO' AND COLUMN_NAME = 'NM_PERFIL')
--BEGIN
--	ALTER TABLE TB_PERFIL_ACESSO ADD NM_PERFIL VARCHAR(255)
--END
--GO


----Insert Padrao
--IF NOT EXISTS(SELECT * FROM TB_PERFIL_ACESSO WHERE NM_PERFIL = 'ADMIN')
--BEGIN
--	INSERT INTO TB_PERFIL_ACESSO VALUES ('ADMIN')
--END
--GO
--
--IF NOT EXISTS(SELECT * FROM TB_PERFIL_ACESSO WHERE NM_PERFIL = 'USUARIO')
--BEGIN
--	INSERT INTO TB_PERFIL_ACESSO VALUES ('USUARIO')
--END
--GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_USUARIO_HAS_PERFIL')
BEGIN
	DROP TABLE TB_USUARIO_HAS_PERFIL
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_PERFIL_ACESSO')
BEGIN
	DROP TABLE TB_PERFIL_ACESSO
END
GO