IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_OFERTA')
BEGIN
	CREATE TABLE TB_OFERTA(
		ID_OFERTA INT IDENTITY(1,1) PRIMARY KEY
	)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_OFERTA' AND COLUMN_NAME = 'ID_PRODUTO')
BEGIN
	ALTER TABLE TB_OFERTA ADD ID_PRODUTO INT
END
GO


