IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_CLIENTE')
BEGIN
	CREATE TABLE TB_CLIENTE(
		ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY
	)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CLIENTE' AND COLUMN_NAME = 'NOME')
BEGIN
	ALTER TABLE TB_CLIENTE ADD NOME VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CLIENTE' AND COLUMN_NAME = 'CPF_CNPJ')
BEGIN
	ALTER TABLE TB_CLIENTE ADD CPF_CNPJ VARCHAR(20)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CLIENTE' AND COLUMN_NAME = 'NU_TELEFONE')
BEGIN
	ALTER TABLE TB_CLIENTE ADD NU_TELEFONE VARCHAR(20)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CLIENTE' AND COLUMN_NAME = 'ID_CLIENTE_ENDERECO')
BEGIN
	ALTER TABLE TB_CLIENTE ADD ID_CLIENTE_ENDERECO INT
END
GO







