IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_BINA')
BEGIN
	CREATE TABLE TB_BINA(
		ID_BINA INT IDENTITY(1,1) PRIMARY KEY
	)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_BINA' AND COLUMN_NAME = 'TIPO')
BEGIN
	ALTER TABLE TB_BINA ADD TIPO VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_BINA' AND COLUMN_NAME = 'NUMERO')
BEGIN
	ALTER TABLE TB_BINA ADD NUMERO VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_BINA' AND COLUMN_NAME = 'STATUS')
BEGIN
	ALTER TABLE TB_BINA ADD STATUS VARCHAR(255)
END
GO


IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_BINA' AND COLUMN_NAME = 'DATA')
BEGIN
	ALTER TABLE TB_BINA ADD DATA DATE
END
GO


