IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_USUARIO')
BEGIN
	CREATE TABLE TB_USUARIO(
		ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY
	)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_USUARIO' AND COLUMN_NAME = 'LOGIN')
BEGIN
	ALTER TABLE TB_USUARIO ADD LOGIN VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_USUARIO' AND COLUMN_NAME = 'SENHA')
BEGIN
	ALTER TABLE TB_USUARIO ADD SENHA VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_USUARIO' AND COLUMN_NAME = 'TEMA')
BEGIN
	ALTER TABLE TB_USUARIO ADD TEMA VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_USUARIO' AND COLUMN_NAME = 'TIPO_ACESSO')
BEGIN
	ALTER TABLE TB_USUARIO ADD TIPO_ACESSO VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_USUARIO' AND COLUMN_NAME = 'DT_ULTIMO_LOGIN')
BEGIN
	ALTER TABLE TB_USUARIO ADD DT_ULTIMO_LOGIN DATETIME
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_USUARIO' AND COLUMN_NAME = 'DT_CRIACAO')
BEGIN
	ALTER TABLE TB_USUARIO ADD DT_CRIACAO DATETIME
END
GO


--Insert Padrao
IF NOT EXISTS(SELECT * FROM TB_USUARIO WHERE LOGIN = 'admin')
BEGIN
	INSERT INTO TB_USUARIO(LOGIN, SENHA,TIPO_ACESSO,DT_CRIACAO) VALUES ('admin','19b6OGncj_oe', 'ADMIN' ,GETDATE())
END
GO


--Updates
IF EXISTS(SELECT * FROM TB_USUARIO WHERE LOGIN = 'admin')
BEGIN
	update TB_USUARIO set SENHA = '19b6OGncj_oe'  WHERE LOGIN = 'admin'
END
GO

IF EXISTS(SELECT * FROM TB_USUARIO WHERE LOGIN = 'admin' AND (TIPO_ACESSO <> 'ADMIN' OR TIPO_ACESSO IS NULL))
BEGIN
	update TB_USUARIO set TIPO_ACESSO = 'ADMIN'  WHERE LOGIN = 'admin'
END
GO


