--IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_USUARIO_HAS_PERFIL')
--BEGIN
--	CREATE TABLE TB_USUARIO_HAS_PERFIL(
--		ID_USUARIO INT ,
--		ID_PERFIL_ACESSO INT
--	)
--END
--GO
--
--IF NOT EXISTS(select * from TB_USUARIO_HAS_PERFIL 
--			  where ID_USUARIO = (select ID_USUARIO from TB_USUARIO where LOGIN = 'admin')
--			  AND ID_PERFIL_ACESSO = (select ID_PERFIL_ACESSO from TB_PERFIL_ACESSO where NM_PERFIL = 'ADMIN')
--			)
--BEGIN
--	INSERT INTO TB_USUARIO_HAS_PERFIL (ID_USUARIO, ID_PERFIL_ACESSO) VALUES ((select ID_USUARIO from TB_USUARIO where LOGIN = 'admin'),(select ID_PERFIL_ACESSO from TB_PERFIL_ACESSO where NM_PERFIL = 'ADMIN'))
--END 
--GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_USUARIO_HAS_PERFIL')
BEGIN
	DROP TABLE TB_USUARIO_HAS_PERFIL
END
GO