IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_ENDERECO')
BEGIN
	CREATE TABLE TB_ENDERECO(
		ID_ENDERECO INT IDENTITY(1,1) PRIMARY KEY
	)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_ENDERECO' AND COLUMN_NAME = 'LOGRADOURO')
BEGIN
	ALTER TABLE TB_ENDERECO ADD LOGRADOURO VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_ENDERECO' AND COLUMN_NAME = 'CEP')
BEGIN
	ALTER TABLE TB_ENDERECO ADD CEP VARCHAR(8)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_ENDERECO' AND COLUMN_NAME = 'BAIRRO')
BEGIN
	ALTER TABLE TB_ENDERECO ADD BAIRRO VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_ENDERECO' AND COLUMN_NAME = 'CIDADE')
BEGIN
	ALTER TABLE TB_ENDERECO ADD CIDADE VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_ENDERECO' AND COLUMN_NAME = 'ESTADO')
BEGIN
	ALTER TABLE TB_ENDERECO ADD ESTADO VARCHAR(2)
END
GO



