IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TB_PEDIDO')
BEGIN
	CREATE TABLE TB_PEDIDO(
		ID_PEDIDO INT IDENTITY(1,1) PRIMARY KEY
	)
END
GO



IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'VALOR_TOTAL')
BEGIN
	ALTER TABLE TB_PEDIDO ADD VALOR_TOTAL NUMERIC(17,2)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'FORMA_PAGAMENTO')
BEGIN
	ALTER TABLE TB_PEDIDO ADD FORMA_PAGAMENTO VARCHAR(100)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'TROCO')
BEGIN
	ALTER TABLE TB_PEDIDO ADD TROCO NUMERIC(17,2)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'DATA')
BEGIN
	ALTER TABLE TB_PEDIDO ADD DATA DATE
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'STATUS')
BEGIN
	ALTER TABLE TB_PEDIDO ADD STATUS VARCHAR(50)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'TAXA_ENTREGA')
BEGIN
	ALTER TABLE TB_PEDIDO ADD TAXA_ENTREGA NUMERIC(19,2)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'VALOR_DESCONTO')
BEGIN
	ALTER TABLE TB_PEDIDO ADD VALOR_DESCONTO NUMERIC(19,2)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'OBSERVACAO')
BEGIN
	ALTER TABLE TB_PEDIDO ADD OBSERVACAO VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'TELEFONE_CLIENTE')
BEGIN
	ALTER TABLE TB_PEDIDO ADD TELEFONE_CLIENTE VARCHAR(14)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'DOCUMENTO_CLIENTE')
BEGIN
	ALTER TABLE TB_PEDIDO ADD DOCUMENTO_CLIENTE VARCHAR(60)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'NOME_CLIENTE')
BEGIN
	ALTER TABLE TB_PEDIDO ADD NOME_CLIENTE VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'LOGRADOURO')
BEGIN
	ALTER TABLE TB_PEDIDO ADD LOGRADOURO VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'NUM_RES')
BEGIN
	ALTER TABLE TB_PEDIDO ADD NUM_RES VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'COMPLEMENTO')
BEGIN
	ALTER TABLE TB_PEDIDO ADD COMPLEMENTO VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'BAIRRO')
BEGIN
	ALTER TABLE TB_PEDIDO ADD BAIRRO VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'ENTREGADOR')
BEGIN
	ALTER TABLE TB_PEDIDO ADD ENTREGADOR VARCHAR(255)
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'IC_COBRAR_TAXA')
BEGIN
	ALTER TABLE TB_PEDIDO ADD IC_COBRAR_TAXA BIT
END
GO


	
--Drops columns não utilizadas	
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'ID_CLIENTE')
BEGIN
	ALTER TABLE TB_PEDIDO DROP COLUMN ID_CLIENTE
END
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'ID_ENTREGADOR')
BEGIN

	IF EXISTS(select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'ID_ENTREGADOR' AND CONSTRAINT_NAME LIKE 'FK%')
	BEGIN
		DECLARE @nameFK VARCHAR(255) = (select TOP 1 CONSTRAINT_NAME from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'ID_ENTREGADOR' AND CONSTRAINT_NAME LIKE 'FK%')

		DECLARE @command NVARCHAR(255) = 'ALTER TABLE TB_PEDIDO DROP CONSTRAINT ' + @nameFK;

		EXEC sp_executesql @command
	END

	ALTER TABLE TB_PEDIDO DROP COLUMN ID_ENTREGADOR
END
GO


IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_PEDIDO' AND COLUMN_NAME = 'ID_FORMA_PAGAMENTO')
BEGIN
	ALTER TABLE TB_PEDIDO DROP COLUMN ID_FORMA_PAGAMENTO
END
GO
